version: 2
jobs:
  build:
    docker:

    - image: circleci/node:10-browsers-legacy

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name: Install dependencies
        command: npm ci

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    #    - run:
    #        name: Run Linter
    #        command: npm run lint

    - run:
        name: Install flow type
        command: npm run flow:typed

    - run:
        name: Run flow
        command: npm run flow

  deploy_prod:
    docker:
    - image: circleci/node:10-browsers-legacy

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package-lock.json" }}

    - run:
        name: Avoid unknown hosts for server
        command: echo -e "Host $DROPLET_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

    - run:
        name: Deploy to server
        command: |
          ssh -v $DROPLET_USER@$DROPLET_IP "cd ~/Woollar-react-dashboard;"
          git pull
          npm install
          npm run build
          exit 0

    - add_ssh_keys:
        fingerprints:
        - $SSH_FINGERPRINT


workflows:
  version: 2
  build_deploy:
    jobs:
    - build
    - deploy_prod:
        requires:
        - build
        filters:
          branches:
            only: master


