version: 2
jobs:
  build:
    docker:

    - image: circleci/node:10-browsers-legacy

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name: Install dependencies
        command: npm ci

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    #    - run:
    #        name: Run Linter
    #        command: npm run lint

    - run:
        name: Install flow type
        command: npm run flow:typed

    - run:
        name: Run flow
        command: npm run flow

  deploy_prod:
    docker:
    - image: circleci/node:10-browsers-legacy

    steps:
    - checkout

    - add_ssh_keys:
        fingerprints:
        - $SSH_FINGERPRINT

    - deploy:
        command: |
          echo 'http://157.230.28.204 ecdsa-sha2-nistp256 ~/.ssh/id_ecdsa.pub' >> ~/.ssh/known_hosts
          echo 'http://157.230.28.204 ssh-rsa ~/.ssh/id_rsa.pub' >> ~/.ssh/known_hosts
          ssh -v $DROPLET_USER@$DROPLET_IP


workflows:
  version: 2
  build_deploy:
    jobs:
    - build
    - deploy_prod:
        requires:
        - build
        filters:
          branches:
            only: master


